### PR TITLE
broke ur code

### PR DESCRIPTION
**Pull request by RandoNandoz**

### CODE REVIEW

**Comment by RandoNandoz** [comment]
accept the pr

**Comment by RandoNandoz** [comment]
accept the pr

**Comment by RandoNandoz** [comment]
accept the pr

**Comment by RandoNandoz** [comment]
accept the pr

**Review by rethinkingrn — APPROVED** [review]
prob a bitcoin miner but sure

**Comment by RandoNandoz** [comment]
accept the pr

**Pull request merged**
